Module2 task2
htmlacademy-adaptive/53877-cat-energy-21 pull request #3
Opened 2020-11-17 14:29 UTC by Katakun

2020-11-17 16:46 UTC, DoberBober commented on source/form.html
> +  <h1 class="page-main__heading">Подбор программы</h1>
Заголовок на третьей странице такой же. Его можно смело вынести в блок.

2020-11-17 16:48 UTC, DoberBober commented on source/form.html
> +            <input class="cat-info__input-text" type="radio" id="cat-mass" name="food-goal">
У тебя сейчас у текстовых полей и у радиокнопок одинаковые классы. Лучше сделай разные, чтобы потом легче было. (У радио дополнительно добавь visually-hidden, их надо будет скрыть.)

2020-11-17 16:49 UTC, DoberBober commented on source/form.html
> +            <label class="cat-info__label" for="cat-slim">Имя:*</label>
У радио лейблы кривые. Копировал сверху, видимо.

2020-11-17 16:49 UTC, DoberBober commented on source/form.html
> +            <input class="cat-info__input-text" type="text" id="cat-phone" value="8 (960) 900-60-90">
type="tel"?

2020-11-17 16:50 UTC, DoberBober commented on source/form.html
> +        <textarea class="cat-info__input-text cat-info__input-text--comment"
Вместо value сделай placeholder. Разница в том, что value человеку придётся удалять, чтобы ввести свой текст.

2020-11-17 16:51 UTC, DoberBober commented on source/form.html
> +            <input class="cat-info__input-text" type="checkbox" id="sweetener" checked>
Тоже поменять класс лучше и добавить visually-hidden.

2020-11-17 16:51 UTC, DoberBober requested changes
Внеси правки с предыдущего пулреквеста тоже и скидывай на повторную.

2020-11-18 05:25 UTC, Katakun commented on source/form.html
> +  <h1 class="page-main__heading">Подбор программы</h1>
Переименовал как блок.

2020-11-18 05:29 UTC, Katakun commented on source/form.html
> +            <input class="cat-info__input-text" type="radio" id="cat-mass" name="food-goal">
сделал.

2020-11-18 05:33 UTC, Katakun commented on source/form.html
> +            <label class="cat-info__label" for="cat-slim">Имя:*</label>
ага, не заметил.

2020-11-18 05:35 UTC, Katakun commented on source/form.html
> +            <input class="cat-info__input-text" type="text" id="cat-phone" value="8 (960) 900-60-90">
точно.

2020-11-18 05:37 UTC, Katakun commented on source/form.html
> +        <textarea class="cat-info__input-text cat-info__input-text--comment"
сделал

2020-11-18 05:39 UTC, Katakun commented on source/form.html
> +            <input class="cat-info__input-text" type="checkbox" id="sweetener" checked>
сделал

2020-11-18 07:12 UTC, merged