Разметил страницу каталога
htmlacademy-adaptive/53877-cat-energy-21 pull request #4
Opened 2020-11-18 09:39 UTC by Katakun

2020-11-18 11:13 UTC, DoberBober commented on source/catalog
> +        <h3 class="product-card__title">Cat Energy PRO 500 г</h3>
Ссылка на товар же.

2020-11-18 11:13 UTC, DoberBober commented on source/catalog
> +          <img src="https://via.placeholder.com/68x86" width="68" height="86" alt="Стаканчик с едой для котов">
И картинку оберни в ссылку.

2020-11-18 11:14 UTC, DoberBober commented on source/catalog
> +        <button class="product-card__button button" type="button">Заказать</button>
Не кнопка, а ссылка. Для доступности.

2020-11-18 11:14 UTC, DoberBober commented on source/catalog
> +    <ul class="extra-catalog_list">
Одного знака _ не хватает.

2020-11-18 11:17 UTC, DoberBober requested changes
Поправь это, чтобы с разметкой закончить. Не будем на следующий пулреквест тащить, хоть и мелочи.

2020-11-19 01:33 UTC, Katakun commented on source/catalog
> +        <h3 class="product-card__title">Cat Energy PRO 500 г</h3>
сделал

2020-11-19 01:34 UTC, Katakun commented on source/catalog
> +          <img src="https://via.placeholder.com/68x86" width="68" height="86" alt="Стаканчик с едой для котов">
<div> заменил на <а> норм?

2020-11-19 01:37 UTC, Katakun commented on source/catalog
> +        <button class="product-card__button button" type="button">Заказать</button>
Сделал. Да, надо было сперва ТЗ читать.

2020-11-19 01:46 UTC, Katakun commented on source/catalog
> +    <ul class="extra-catalog_list">
Сделал.

2020-11-19 07:22 UTC, merged